// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/interfaces/featureflag_interfaces.go

// Package mock is a generated GoMock package.
package featureflag

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFeatureFlagRepository is a mock of Adapter interface.
type MockFeatureFlagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagRepositoryMockRecorder
}

// MockFeatureFlagRepositoryMockRecorder is the mock recorder for MockFeatureFlagRepository.
type MockFeatureFlagRepositoryMockRecorder struct {
	mock *MockFeatureFlagRepository
}

// NewMockFeatureFlagRepository creates a new mock instance.
func NewMockFeatureFlagRepository(ctrl *gomock.Controller) *MockFeatureFlagRepository {
	mock := &MockFeatureFlagRepository{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagRepository) EXPECT() *MockFeatureFlagRepositoryMockRecorder {
	return m.recorder
}

// DeleteFF mocks base method.
func (m *MockFeatureFlagRepository) DeleteFF(ctx context.Context, project, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFF", ctx, project, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFF indicates an expected call of DeleteFF.
func (mr *MockFeatureFlagRepositoryMockRecorder) DeleteFF(ctx, project, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFF", reflect.TypeOf((*MockFeatureFlagRepository)(nil).DeleteFF), ctx, project, key)
}

// GetAllFF mocks base method.
func (m *MockFeatureFlagRepository) GetAllFF(ctx context.Context, project string) (map[string]Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFF", ctx, project)
	ret0, _ := ret[0].(map[string]Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFF indicates an expected call of GetAllFF.
func (mr *MockFeatureFlagRepositoryMockRecorder) GetAllFF(ctx, project interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFF", reflect.TypeOf((*MockFeatureFlagRepository)(nil).GetAllFF), ctx, project)
}

// GetFF mocks base method.
func (m *MockFeatureFlagRepository) GetFF(ctx context.Context, project, key string) (Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFF", ctx, project, key)
	ret0, _ := ret[0].(Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFF indicates an expected call of GetFF.
func (mr *MockFeatureFlagRepositoryMockRecorder) GetFF(ctx, project, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFF", reflect.TypeOf((*MockFeatureFlagRepository)(nil).GetFF), ctx, project, key)
}

// ListProjects mocks base method.
func (m *MockFeatureFlagRepository) ListProjects(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockFeatureFlagRepositoryMockRecorder) ListProjects(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockFeatureFlagRepository)(nil).ListProjects), ctx)
}

// SaveFF mocks base method.
func (m *MockFeatureFlagRepository) SaveFF(ctx context.Context, project string, input Entity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFF", ctx, project, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFF indicates an expected call of SaveFF.
func (mr *MockFeatureFlagRepositoryMockRecorder) SaveFF(ctx, project, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFF", reflect.TypeOf((*MockFeatureFlagRepository)(nil).SaveFF), ctx, project, input)
}
